### ISSUE TITLE
Upgrade to null safety

### ISSUE THREAD

**Issue by sachin052** [davigmacode/flutter_smart_select#76]

**Comment by mainawycliffe** [comment]
Is there someone working on this?

**Comment by JErazo7** [comment]
This is necessary

**Comment by simonkimi** [comment]
> Is there someone working on this? If no one, I would not mind tackling it.

Any progress?

**Comment by iktakahiro** [comment]
I've created PR https://github.com/davigmacode/flutter_smart_select/pull/82 but this is a WIP. If anyone can figure out what's causing the error, I need your help.

**Comment by iktakahiro** [comment]
I've fixed all failure tests!!

If you would like to use it before merging, set the git repository URI to your pubspec.yaml

```yaml
  smart_select:
    git:
      url: git@github.com:iktakahiro/flutter_smart_select.git
      ref: null-safety
```

**Comment by celvinren** [comment]
> I've fixed all failure tests!!
> 
> If you would like to use it before merging, set the git repository URI to your pubspec.yaml
> 
> ```yaml
>   smart_select:
>     git:
>       url: git@github.com:iktakahiro/flutter_smart_select.git
>       ref: null-safety
> ```

Could you share to public?

**Comment by iktakahiro** [comment]
@celvinren thanks for your mention.

It's a public repository. https://github.com/iktakahiro/flutter_smart_select/tree/null-safety

if `Permission denied` error occurs when `pub get`, that may be due to the cache.

Or try the following

```yaml
  smart_select:
    git:
      url: https://github.com/iktakahiro/flutter_smart_select.git
      ref: null-safety
```

**Comment by alfiepoleon** [comment]
@iktakahiro when I check for packages without null-safety, this comes up.
```bash
➜ flutter pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name             Current       Upgradable    Resolvable    Latest        

direct dependencies:    
flutter_datetime_picker  ✗1.4.0 (git)  ✗1.4.0 (git)  ✗1.4.0 (git)  ✗1.4.0 (git)  
```
And when I try to migrate ignoring the package check, throws an error too.
```bash
➜ dart migrate --skip-import-check
Migrating /home/alfie/dev/work/coordinator/coordinator-app

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------/]Warning: package has unmigrated dependencies.

Continuing due to the presence of `--skip-import-check`.  To see a complete
list of the unmigrated dependencies, re-run without the `--skip-import-check`
flag.


27 analysis issues found:
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/screens/contacts/category_member.screen.dart:279:55 • (undefined_getter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/screens/contacts/category_member.screen.dart:280:53 • (undefined_getter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/screens/contacts/category_member.screen.dart:281:45 • (undefined_getter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/screens/contacts/category_user_list_item.dart:432:43 • (undefined_getter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/screens/contacts/category_user_list_item.dart:433:41 • (undefined_getter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/screens/contacts/category_user_list_item.dart:434:33 • (undefined_getter)
  error • The named parameter 'value' isn't defined at lib/screens/contacts/csv_contacts_import.screen.dart:142:19 • (undefined_named_parameter)
  error • The named parameter 'activeColor' isn't defined at lib/screens/contacts/csv_contacts_import.screen.dart:145:23 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib/screens/contacts/device_contacts_import.screen.dart:157:37 • (undefined_named_parameter)
  error • The named parameter 'activeColor' isn't defined at lib/screens/contacts/device_contacts_import.screen.dart:160:41 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib/screens/organization/organization_operating_hours.widget.dart:262:35 • (undefined_named_parameter)
  error • The named parameter 'activeColor' isn't defined at lib/screens/organization/organization_operating_hours.widget.dart:282:62 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib/screens/organization/organization_operating_hours.widget.dart:325:33 • (undefined_named_parameter)
  error • The named parameter 'activeColor' isn't defined at lib/screens/organization/organization_operating_hours.widget.dart:346:60 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib/screens/organization/organization_operating_hours.widget.dart:426:25 • (undefined_named_parameter)
  error • The named parameter 'activeColor' isn't defined at lib/screens/organization/organization_operating_hours.widget.dart:450:52 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib/screens/organization/organization_shareholders.widget.dart:434:29 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib/screens/profile/general_profile.widget.dart:392:43 • (undefined_named_parameter)
  error • The named parameter 'activeColor' isn't defined at lib/screens/profile/general_profile.widget.dart:407:70 • (undefined_named_parameter)
  error • The named parameter 'value' isn't defined at lib/screens/profile/general_profile.widget.dart:517:57 • (undefined_named_parameter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<CountryCode>' at lib/screens/profile/general_profile.widget.dart:525:69 • (undefined_getter)
  error • The getter 'valueDisplay' isn't defined for the type 'S2SingleState<CountryCode>' at lib/screens/profile/general_profile.widget.dart:525:94 • (undefined_getter)
  error • The named parameter 'value' isn't defined at lib/utils/common_widgets.dart:60:7 • (undefined_named_parameter)
  error • The named parameter 'activeColor' isn't defined at lib/utils/common_widgets.dart:63:11 • (undefined_named_parameter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/utils/common_widgets.dart:88:25 • (undefined_getter)
  error • The getter 'value' isn't defined for the type 'S2SingleState<dynamic>' at lib/utils/common_widgets.dart:90:34 • (undefined_getter)
  error • The argument type 'dynamic Function(S2SingleState<dynamic>)' can't be assigned to the parameter type 'void Function(S2SingleSelected<dynamic>)' at lib/utils/common_widgets.dart:99:7 • (argument_type_not_assignable)

The migration tool didn't start, due to analysis errors.
```

My pubspec.yaml
```yaml
...
  shared_preferences: ^2.0.5
  smart_select:
    git:
      url: https://github.com/iktakahiro/flutter_smart_select.git
      ref: null-safety
  smooth_page_indicator: ^0.3.0-nullsafety.0
...
```

**Comment by alfiepoleon** [comment]
Seems as if there are some breaking changes with the git link. e.g This used to work
```dart
SmartSelect<CountryCode>.single(
  value: ...,
```
but now `value` isn't defined
Among others like `state.value` and `state.valueDisplay` not being defined.
Is there documentation for what has changed?

**Comment by simonkimi** [comment]
> 
> 
> Seems as if there are some breaking changes with the git link. e.g This used to work
> 
> ```dart
> SmartSelect<CountryCode>.single(
>   value: ...,
> ```
> 
> but now `value` isn't defined
> Among others like `state.value` and `state.valueDisplay` not being defined.
> Is there documentation for what has changed?

`value` has been replaced with `selectedValue`
I found it in the history of commit.

**Comment by FRANIAZA** [comment]
I can't figure out whether I'm doing something wrong or there is a problem with this null-safe version.
I'm getting the following error: 
```
E/flutter (13256): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type '(List<String?>?) => Future<List<S2Choice<String?>>?>' is not a subtype of type '((List<String>?) => Future<List<S2Choice<String>>?>)?' of 'defaultResolver'
E/flutter (13256): #0      S2MultiState.resolveSelected (package:smart_select/src/widget.dart:1964:11)
E/flutter (13256): #1      S2State.initState (package:smart_select/src/widget.dart:1669:5)
```

My code is the following: 
```dart
class SmartMultiSelectBuilder extends FormField<List<String>>{
  final FormFieldValidator<List<String>>? validator;
  final List<Map<String, String>> choiceItems;
  final String title;
  final String? placeholder;
  final List<String>? initialValue;
  final bool isGrouped;
  final IconData icon;
  final Function(List<String>?) onChanged;

  SmartMultiSelectBuilder({
    this.validator,
    required this.choiceItems,
    required this.title,
    this.placeholder,
    this.initialValue,
    this.isGrouped = false,
    required this.icon,
    required this.onChanged,
  }) : super(
      initialValue: initialValue,
      validator: validator,
      builder: (FormFieldState<List<String>> state){
        print(initialValue);
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SmartSelect.multiple(
              title: title,
              placeholder: 'placeholder',
              selectedValue: initialValue,

              modalConfig: S2ModalConfig(
                type: S2ModalType.bottomSheet,
                headerStyle: S2ModalHeaderStyle(
                  textStyle: smallTitleStyle,
                  elevation: 3,
                ),
                style: S2ModalStyle(
                  backgroundColor: Colors.white,
                  clipBehavior: Clip.antiAlias,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(kBorderRadius),
                      topRight: Radius.circular(kBorderRadius)
                    )
                  )
                ),
              ),

              choiceGrouped: isGrouped,
              groupConfig: S2GroupConfig(
                useCounter: true,
                headerStyle: S2GroupHeaderStyle(
                    backgroundColor: themeOrangeColor,
                    textStyle: regularTextStyle.copyWith(color: Colors.white)
                )
              ),

              choiceConfig: S2ChoiceConfig(
                  useDivider: true,
                  style: S2ChoiceStyle(
                    padding: EdgeInsets.symmetric(horizontal: 5),
                    accentColor: themeOrangeColor, //fill color of checkbox
                    color: Colors.black12, //outline of checkbox
                  )
              ),
              choiceItems: S2Choice.listFrom<String, Map>(
                source: choiceItems,
                value: (index, item) => item['value']!,
                title: (index, item) => item['title']!,
                group: (index, item) => item['group']!,
              ),

              onChange: (selectState){
                onChanged(selectState!.value as List<String>?);
                state.didChange(selectState.value as List<String>?);
              },

              choiceBuilder: (context, state, choice){
                return ListTile(
                  onTap: () => choice.select!(!choice.selected),
                  title: Text(choice.title!, style: thinTextStyle),
                  tileColor: Colors.white,
                  contentPadding: EdgeInsets.symmetric(horizontal: 15),
                  trailing: Checkbox(
                    checkColor: Colors.white,
                    activeColor: themeOrangeColor,
                    value: choice.selected,
                    onChanged: (value) => choice.select!(!choice.selected),
                  ),
                );
              },
              choiceDividerBuilder: (context, index){
                return Container(
                  color: Colors.white,
                  padding: EdgeInsets.symmetric(horizontal: 6),
                  child: Divider(
                    color: Colors.black26,
                    height: 1,
                    thickness: 0.3,
                  ),
                );
              },
              tileBuilder: (context, selectState) {
                return Column(
                  children: [
                    Container(
                      alignment: Alignment.centerLeft,
                      decoration: kBoxDecorationStyle.copyWith(
                        border: Border.all(
                          color: state.hasError ? Colors.red : Colors.transparent
                        )
                      ),
                      height: 60.0,
                      child: ListTile(
                        contentPadding: EdgeInsets.symmetric(horizontal: 13.5),
                        leading: FaIcon(icon, color: themeOrangeColor),
                        title: Transform(
                          transform: Matrix4.translationValues(-20, 0.0, 0.0),
                          child: selectState.selected.toString() == 'placeholder' ? //se nessun elemento è selezionato valueDisplay restituisce il placeholder
                          Text(placeholder!, style: hintTextStyle) :
                          Text(
                            selectState.selected.toString(),
                            style: textFieldStyle,
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        trailing: FaIcon(
                            FontAwesomeIcons.angleRight,
                            color: Colors.black26,
                            size: 18
                        ),
                        onTap: () => selectState.showModal(),
                      ),
                    ),
                  ],
                );
              },
            ),
            state.hasError?
            Padding(
              padding: EdgeInsets.fromLTRB(20, 3, 0, 0),
              child: Text(
                state.errorText!,
                style: thinTextStyle.copyWith(color: Colors.red)
              ),
            ) :
            Container()
          ],
        );
      }
  );
}
```

**Comment by alfiepoleon** [comment]
> > Seems as if there are some breaking changes with the git link. e.g This used to work
> > ```dart
> > SmartSelect<CountryCode>.single(
> >   value: ...,
> > ```
> > 
> > 
> > but now `value` isn't defined
> > Among others like `state.value` and `state.valueDisplay` not being defined.
> > Is there documentation for what has changed?
> 
> `value` has been replaced with `selectedValue`
> I found it in the history of commit.

Can you please guide me on how to? I have been going through the commit looking for those syntax changes and I have not been successful

**Comment by vasilich6107** [comment]
I released https://pub.dev/packages/flutter_awesome_select with fixed null safety.
Could you check that everything works for you?

**Comment by davigmacode** [comment]
Hi everyone,

I'm really sorry for not maintaining the [smart_select](https://pub.dev/packages/smart_select) package in a long time. It's been a great project, but it's become too difficult for me to maintain, especially since I've been going through a tough time for the past few years.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [smart_select](https://pub.dev/packages/smart_select).

Thanks for your understanding.
